import json
import os

# Define Pre-Intermediate level topics data
pre_intermediate_topics = {
    "pre-intermediate/travel.json": {
        "id": "travel",
        "name": "Du lịch & địa điểm công cộng",
        "level": "pre-intermediate",
        "icon": "✈️",
        "description": "Từ vựng về du lịch, giao thông và các địa điểm công cộng",
        "words": [
            {"word": "Travel", "meaning": "Du lịch", "pos": "verb",
                "example": "I love to travel around the world.", "pronunciation": "/ˈtrævəl/"},
            {"word": "Trip", "meaning": "Chuyến đi", "pos": "noun",
                "example": "We had a wonderful trip to Japan.", "pronunciation": "/trɪp/"},
            {"word": "Journey", "meaning": "Hành trình", "pos": "noun",
                "example": "The journey took five hours.", "pronunciation": "/ˈdʒɜːrni/"},
            {"word": "Vacation", "meaning": "Kỳ nghỉ", "pos": "noun",
                "example": "Summer vacation is coming soon.", "pronunciation": "/veɪˈkeɪʃən/"},
            {"word": "Holiday", "meaning": "Ngày lễ/Nghỉ mát", "pos": "noun",
                "example": "We're going on holiday next week.", "pronunciation": "/ˈhɑːlədeɪ/"},
            {"word": "Tourist", "meaning": "Du khách", "pos": "noun",
                "example": "Many tourists visit Vietnam.", "pronunciation": "/ˈtʊrɪst/"},
            {"word": "Airport", "meaning": "Sân bay", "pos": "noun",
                "example": "The airport is very busy today.", "pronunciation": "/ˈerpɔːrt/"},
            {"word": "Flight", "meaning": "Chuyến bay", "pos": "noun",
                "example": "My flight is delayed.", "pronunciation": "/flaɪt/"},
            {"word": "Airplane", "meaning": "Máy bay", "pos": "noun",
                "example": "The airplane is flying overhead.", "pronunciation": "/ˈerplen/"},
            {"word": "Passport", "meaning": "Hộ chiếu", "pos": "noun",
                "example": "Don't forget your passport.", "pronunciation": "/ˈpæspɔːrt/"},
            {"word": "Visa", "meaning": "Thị thực", "pos": "noun",
                "example": "I need a visa to enter that country.", "pronunciation": "/ˈviːzə/"},
            {"word": "Luggage", "meaning": "Hành lý", "pos": "noun",
                "example": "My luggage is very heavy.", "pronunciation": "/ˈlʌɡɪdʒ/"},
            {"word": "Suitcase", "meaning": "Vali", "pos": "noun",
                "example": "Pack your clothes in the suitcase.", "pronunciation": "/ˈsuːtkeɪs/"},
            {"word": "Hotel", "meaning": "Khách sạn", "pos": "noun",
                "example": "We stayed at a nice hotel.", "pronunciation": "/hoʊˈtel/"},
            {"word": "Motel", "meaning": "Nhà nghỉ", "pos": "noun",
                "example": "The motel is cheap but clean.", "pronunciation": "/moʊˈtel/"},
            {"word": "Hostel", "meaning": "Nhà trọ", "pos": "noun",
                "example": "Students often stay in hostels.", "pronunciation": "/ˈhɑːstəl/"},
            {"word": "Reservation", "meaning": "Đặt chỗ", "pos": "noun",
                "example": "I have a reservation under my name.", "pronunciation": "/ˌrezərˈveɪʃən/"},
            {"word": "Check-in", "meaning": "Làm thủ tục nhận phòng", "pos": "noun",
                "example": "Hotel check-in is at 3 PM.", "pronunciation": "/ˈtʃek ɪn/"},
            {"word": "Check-out", "meaning": "Làm thủ tục trả phòng", "pos": "noun",
                "example": "Check-out time is 11 AM.", "pronunciation": "/ˈtʃek aʊt/"},
            {"word": "Museum", "meaning": "Bảo tàng", "pos": "noun",
                "example": "The museum has ancient artifacts.", "pronunciation": "/mjuˈziːəm/"},
            {"word": "Gallery", "meaning": "Phòng trưng bày", "pos": "noun",
                "example": "The art gallery is beautiful.", "pronunciation": "/ˈɡæləri/"},
            {"word": "Castle", "meaning": "Lâu đài", "pos": "noun",
                "example": "The castle is very old.", "pronunciation": "/ˈkæsəl/"},
            {"word": "Temple", "meaning": "Chùa/Đền", "pos": "noun",
                "example": "The temple is a sacred place.", "pronunciation": "/ˈtempəl/"},
            {"word": "Church", "meaning": "Nhà thờ", "pos": "noun",
                "example": "The church bells are ringing.", "pronunciation": "/tʃɜːrtʃ/"},
            {"word": "Market", "meaning": "Chợ", "pos": "noun",
                "example": "Buy fresh food at the market.", "pronunciation": "/ˈmɑːrkɪt/"},
            {"word": "Square", "meaning": "Quảng trường", "pos": "noun",
                "example": "People gather in the town square.", "pronunciation": "/skwer/"},
            {"word": "Beach", "meaning": "Bãi biển", "pos": "noun",
                "example": "The beach has white sand.", "pronunciation": "/biːtʃ/"},
            {"word": "Mountain", "meaning": "Núi", "pos": "noun",
                "example": "The mountain is very high.", "pronunciation": "/ˈmaʊntən/"},
            {"word": "Forest", "meaning": "Rừng", "pos": "noun",
                "example": "Wild animals live in the forest.", "pronunciation": "/ˈfɔːrəst/"},
            {"word": "Lake", "meaning": "Hồ", "pos": "noun",
                "example": "The lake is very peaceful.", "pronunciation": "/leɪk/"},
            {"word": "River", "meaning": "Sông", "pos": "noun",
                "example": "Fish swim in the river.", "pronunciation": "/ˈrɪvər/"},
            {"word": "Bridge", "meaning": "Cầu", "pos": "noun",
                "example": "Cross the bridge carefully.", "pronunciation": "/brɪdʒ/"},
            {"word": "Island", "meaning": "Đảo", "pos": "noun",
                "example": "The island is surrounded by water.", "pronunciation": "/ˈaɪlənd/"},
            {"word": "Park", "meaning": "Công viên", "pos": "noun",
                "example": "Children play in the park.", "pronunciation": "/pɑːrk/"},
            {"word": "Zoo", "meaning": "Sở thú", "pos": "noun",
                "example": "We saw many animals at the zoo.", "pronunciation": "/zuː/"},
            {"word": "Stadium", "meaning": "Sân vận động", "pos": "noun",
                "example": "The stadium holds 50,000 people.", "pronunciation": "/ˈsteɪdiəm/"},
            {"word": "Theater", "meaning": "Rạp hát", "pos": "noun",
                "example": "We watched a play at the theater.", "pronunciation": "/ˈθiːətər/"},
            {"word": "Cinema", "meaning": "Rạp chiếu phim", "pos": "noun",
                "example": "Let's go to the cinema tonight.", "pronunciation": "/ˈsɪnəmə/"},
            {"word": "Library", "meaning": "Thư viện", "pos": "noun",
                "example": "I borrow books from the library.", "pronunciation": "/ˈlaɪbreri/"},
            {"word": "Hospital", "meaning": "Bệnh viện", "pos": "noun",
                "example": "The hospital is open 24 hours.", "pronunciation": "/ˈhɑːspɪtəl/"},
            {"word": "Bank", "meaning": "Ngân hàng", "pos": "noun",
                "example": "I need to go to the bank.", "pronunciation": "/bæŋk/"},
            {"word": "Post office", "meaning": "Bưu điện", "pos": "noun",
                "example": "Send the letter at the post office.", "pronunciation": "/poʊst ˈɔːfɪs/"},
            {"word": "Station", "meaning": "Ga/Trạm", "pos": "noun",
                "example": "The train station is crowded.", "pronunciation": "/ˈsteɪʃən/"},
            {"word": "Map", "meaning": "Bản đồ", "pos": "noun",
                "example": "Use the map to find your way.", "pronunciation": "/mæp/"},
            {"word": "Guide", "meaning": "Hướng dẫn viên", "pos": "noun",
                "example": "The tour guide was very helpful.", "pronunciation": "/ɡaɪd/"},
            {"word": "Souvenir", "meaning": "Quà lưu niệm", "pos": "noun",
                "example": "I bought souvenirs for my family.", "pronunciation": "/ˌsuːvəˈnɪr/"}
        ]
    },

    "pre-intermediate/health.json": {
        "id": "health",
        "name": "Sức khỏe và bệnh tật",
        "level": "pre-intermediate",
        "icon": "🏥",
        "description": "Từ vựng về sức khỏe, y tế và các bệnh thường gặp",
        "words": [
            {"word": "Health", "meaning": "Sức khỏe", "pos": "noun",
                "example": "Good health is very important.", "pronunciation": "/helθ/"},
            {"word": "Healthy", "meaning": "Khỏe mạnh", "pos": "adjective",
                "example": "Eating vegetables keeps you healthy.", "pronunciation": "/ˈhelθi/"},
            {"word": "Sick", "meaning": "Ốm", "pos": "adjective",
                "example": "I feel sick today.", "pronunciation": "/sɪk/"},
            {"word": "Illness", "meaning": "Bệnh tật", "pos": "noun",
                "example": "He recovered from his illness.", "pronunciation": "/ˈɪlnəs/"},
            {"word": "Disease", "meaning": "Bệnh", "pos": "noun",
                "example": "This disease is contagious.", "pronunciation": "/dɪˈziːz/"},
            {"word": "Pain", "meaning": "Đau", "pos": "noun",
                "example": "The pain in my back is terrible.", "pronunciation": "/peɪn/"},
            {"word": "Hurt", "meaning": "Đau", "pos": "verb",
                "example": "My head hurts.", "pronunciation": "/hɜːrt/"},
            {"word": "Ache", "meaning": "Đau nhức", "pos": "noun",
                "example": "I have a stomach ache.", "pronunciation": "/eɪk/"},
            {"word": "Fever", "meaning": "Sốt", "pos": "noun",
                "example": "The child has a high fever.", "pronunciation": "/ˈfiːvər/"},
            {"word": "Cold", "meaning": "Cảm lạnh", "pos": "noun",
                "example": "I caught a cold yesterday.", "pronunciation": "/koʊld/"},
            {"word": "Flu", "meaning": "Cúm", "pos": "noun",
                "example": "The flu spreads quickly.", "pronunciation": "/fluː/"},
            {"word": "Cough", "meaning": "Ho", "pos": "noun",
                "example": "This cough won't go away.", "pronunciation": "/kɔːf/"},
            {"word": "Sneeze", "meaning": "Hắt hơi", "pos": "verb",
                "example": "Cover your mouth when you sneeze.", "pronunciation": "/sniːz/"},
            {"word": "Headache", "meaning": "Đau đầu", "pos": "noun",
                "example": "I have a terrible headache.", "pronunciation": "/ˈhedeɪk/"},
            {"word": "Toothache", "meaning": "Đau răng", "pos": "noun",
                "example": "See a dentist for your toothache.", "pronunciation": "/ˈtuːθeɪk/"},
            {"word": "Stomachache", "meaning": "Đau bụng", "pos": "noun",
                "example": "Eating too much causes stomachache.", "pronunciation": "/ˈstʌməkeɪk/"},
            {"word": "Backache", "meaning": "Đau lưng", "pos": "noun",
                "example": "Sitting too long causes backache.", "pronunciation": "/ˈbækeɪk/"},
            {"word": "Sore throat", "meaning": "Đau họng", "pos": "noun",
                "example": "Warm tea helps a sore throat.", "pronunciation": "/sɔːr θroʊt/"},
            {"word": "Injury", "meaning": "Chấn thương", "pos": "noun",
                "example": "The sports injury was serious.", "pronunciation": "/ˈɪndʒəri/"},
            {"word": "Wound", "meaning": "Vết thương", "pos": "noun",
                "example": "Clean the wound carefully.", "pronunciation": "/wuːnd/"},
            {"word": "Cut", "meaning": "Vết cắt", "pos": "noun",
                "example": "Put a bandage on the cut.", "pronunciation": "/kʌt/"},
            {"word": "Burn", "meaning": "Vết bỏng", "pos": "noun",
                "example": "Ice helps cool a burn.", "pronunciation": "/bɜːrn/"},
            {"word": "Bruise", "meaning": "Vết bầm", "pos": "noun",
                "example": "The bruise turned purple.", "pronunciation": "/bruːz/"},
            {"word": "Broken bone", "meaning": "Xương gãy", "pos": "noun",
                "example": "A broken bone needs time to heal.", "pronunciation": "/ˈbroʊkən boʊn/"},
            {"word": "Medicine", "meaning": "Thuốc", "pos": "noun",
                "example": "Take this medicine twice daily.", "pronunciation": "/ˈmedəsən/"},
            {"word": "Pill", "meaning": "Viên thuốc", "pos": "noun",
                "example": "Swallow the pill with water.", "pronunciation": "/pɪl/"},
            {"word": "Tablet", "meaning": "Viên thuốc", "pos": "noun",
                "example": "Take one tablet before meals.", "pronunciation": "/ˈtæblət/"},
            {"word": "Injection", "meaning": "Tiêm", "pos": "noun",
                "example": "The injection prevents disease.", "pronunciation": "/ɪnˈdʒekʃən/"},
            {"word": "Vaccine", "meaning": "Vắc-xin", "pos": "noun",
                "example": "Get the vaccine to stay healthy.", "pronunciation": "/vækˈsiːn/"},
            {"word": "Treatment", "meaning": "Điều trị", "pos": "noun",
                "example": "The treatment was successful.", "pronunciation": "/ˈtriːtmənt/"},
            {"word": "Cure", "meaning": "Chữa khỏi", "pos": "verb",
                "example": "Rest will cure your headache.", "pronunciation": "/kjʊr/"},
            {"word": "Heal", "meaning": "Lành", "pos": "verb",
                "example": "The wound will heal in a week.", "pronunciation": "/hiːl/"},
            {"word": "Recovery", "meaning": "Hồi phục", "pos": "noun",
                "example": "His recovery was very quick.", "pronunciation": "/rɪˈkʌvəri/"},
            {"word": "Emergency", "meaning": "Cấp cứu", "pos": "noun",
                "example": "Call 911 in an emergency.", "pronunciation": "/ɪˈmɜːrdʒənsi/"},
            {"word": "Ambulance", "meaning": "Xe cứu thương", "pos": "noun",
                "example": "The ambulance arrived quickly.", "pronunciation": "/ˈæmbjələns/"},
            {"word": "Surgery", "meaning": "Phẫu thuật", "pos": "noun",
                "example": "The surgery was successful.", "pronunciation": "/ˈsɜːrdʒəri/"},
            {"word": "Operation", "meaning": "Ca phẫu thuật", "pos": "noun",
                "example": "The operation lasted three hours.", "pronunciation": "/ˌɑːpəˈreɪʃən/"},
            {"word": "Appointment", "meaning": "Cuộc hẹn", "pos": "noun",
                "example": "I have a doctor's appointment.", "pronunciation": "/əˈpɔɪntmənt/"},
            {"word": "Examination", "meaning": "Khám bệnh", "pos": "noun",
                "example": "The examination showed good health.", "pronunciation": "/ɪɡˌzæməˈneɪʃən/"},
            {"word": "Diagnosis", "meaning": "Chẩn đoán", "pos": "noun",
                "example": "The diagnosis was accurate.", "pronunciation": "/ˌdaɪəɡˈnoʊsəs/"},
            {"word": "Symptom", "meaning": "Triệu chứng", "pos": "noun",
                "example": "Fever is a common symptom.", "pronunciation": "/ˈsɪmptəm/"},
            {"word": "Patient", "meaning": "Bệnh nhân", "pos": "noun",
                "example": "The patient is recovering well.", "pronunciation": "/ˈpeɪʃənt/"},
            {"word": "Prescription", "meaning": "Đơn thuốc", "pos": "noun",
                "example": "Follow the prescription carefully.", "pronunciation": "/prɪˈskrɪpʃən/"},
            {"word": "Pharmacy", "meaning": "Hiệu thuốc", "pos": "noun",
                "example": "Buy medicine at the pharmacy.", "pronunciation": "/ˈfɑːrməsi/"},
            {"word": "Dentist", "meaning": "Nha sĩ", "pos": "noun",
                "example": "Visit the dentist regularly.", "pronunciation": "/ˈdentɪst/"},
            {"word": "Checkup", "meaning": "Khám sức khỏe", "pos": "noun",
                "example": "Annual checkups are important.", "pronunciation": "/ˈtʃekʌp/"}
        ]
    },

    "pre-intermediate/technology.json": {
        "id": "technology",
        "name": "Công nghệ cơ bản",
        "level": "pre-intermediate",
        "icon": "💻",
        "description": "Từ vựng về công nghệ, máy tính và thiết bị điện tử",
        "words": [
            {"word": "Technology", "meaning": "Công nghệ", "pos": "noun",
                "example": "Technology changes our lives.", "pronunciation": "/tekˈnɑːlədʒi/"},
            {"word": "Computer", "meaning": "Máy tính", "pos": "noun",
                "example": "I use a computer for work.", "pronunciation": "/kəmˈpjuːtər/"},
            {"word": "Laptop", "meaning": "Máy tính xách tay", "pos": "noun",
                "example": "My laptop is very light.", "pronunciation": "/ˈlæptɑːp/"},
            {"word": "Desktop", "meaning": "Máy tính để bàn", "pos": "noun",
                "example": "Desktop computers are powerful.", "pronunciation": "/ˈdesktɑːp/"},
            {"word": "Tablet", "meaning": "Máy tính bảng", "pos": "noun",
                "example": "Tablets are good for reading.", "pronunciation": "/ˈtæblət/"},
            {"word": "Smartphone", "meaning": "Điện thoại thông minh", "pos": "noun",
                "example": "Everyone has a smartphone now.", "pronunciation": "/ˈsmɑːrtfoʊn/"},
            {"word": "Phone", "meaning": "Điện thoại", "pos": "noun",
                "example": "My phone battery is low.", "pronunciation": "/foʊn/"},
            {"word": "Screen", "meaning": "Màn hình", "pos": "noun",
                "example": "The screen is very clear.", "pronunciation": "/skriːn/"},
            {"word": "Monitor", "meaning": "Màn hình máy tính", "pos": "noun",
                "example": "I need a bigger monitor.", "pronunciation": "/ˈmɑːnətər/"},
            {"word": "Keyboard", "meaning": "Bàn phím", "pos": "noun",
                "example": "This keyboard is comfortable.", "pronunciation": "/ˈkiːbɔːrd/"},
            {"word": "Mouse", "meaning": "Chuột máy tính", "pos": "noun",
                "example": "Click the mouse to select.", "pronunciation": "/maʊs/"},
            {"word": "Printer", "meaning": "Máy in", "pos": "noun",
                "example": "The printer needs more ink.", "pronunciation": "/ˈprɪntər/"},
            {"word": "Scanner", "meaning": "Máy quét", "pos": "noun",
                "example": "Use the scanner for documents.", "pronunciation": "/ˈskænər/"},
            {"word": "Camera", "meaning": "Máy ảnh", "pos": "noun",
                "example": "This camera takes great photos.", "pronunciation": "/ˈkæmərə/"},
            {"word": "Internet", "meaning": "Mạng internet", "pos": "noun",
                "example": "Internet connects the world.", "pronunciation": "/ˈɪntərnet/"},
            {"word": "Website", "meaning": "Trang web", "pos": "noun",
                "example": "Visit our website for information.", "pronunciation": "/ˈwebsaɪt/"},
            {"word": "Email", "meaning": "Thư điện tử", "pos": "noun",
                "example": "Send me an email later.", "pronunciation": "/ˈiːmeɪl/"},
            {"word": "Password", "meaning": "Mật khẩu", "pos": "noun",
                "example": "Create a strong password.", "pronunciation": "/ˈpæswɜːrd/"},
            {"word": "Software", "meaning": "Phần mềm", "pos": "noun",
                "example": "Install the latest software.", "pronunciation": "/ˈsɔːftwer/"},
            {"word": "Hardware", "meaning": "Phần cứng", "pos": "noun",
                "example": "Hardware includes all physical parts.", "pronunciation": "/ˈhɑːrdwer/"},
            {"word": "Program", "meaning": "Chương trình", "pos": "noun",
                "example": "This program is very useful.", "pronunciation": "/ˈproʊɡræm/"},
            {"word": "Application", "meaning": "Ứng dụng", "pos": "noun",
                "example": "Download this application.", "pronunciation": "/ˌæplɪˈkeɪʃən/"},
            {"word": "App", "meaning": "Ứng dụng", "pos": "noun",
                "example": "There's an app for everything.", "pronunciation": "/æp/"},
            {"word": "File", "meaning": "Tập tin", "pos": "noun",
                "example": "Save the file on your computer.", "pronunciation": "/faɪl/"},
            {"word": "Folder", "meaning": "Thư mục", "pos": "noun",
                "example": "Put files in the correct folder.", "pronunciation": "/ˈfoʊldər/"},
            {"word": "Document", "meaning": "Tài liệu", "pos": "noun",
                "example": "Edit the document carefully.", "pronunciation": "/ˈdɑːkjəmənt/"},
            {"word": "Data", "meaning": "Dữ liệu", "pos": "noun",
                "example": "Back up your data regularly.", "pronunciation": "/ˈdeɪtə/"},
            {"word": "Download", "meaning": "Tải xuống", "pos": "verb",
                "example": "Download the file from the internet.", "pronunciation": "/ˌdaʊnˈloʊd/"},
            {"word": "Upload", "meaning": "Tải lên", "pos": "verb",
                "example": "Upload your photos to the cloud.", "pronunciation": "/ˌʌpˈloʊd/"},
            {"word": "Save", "meaning": "Lưu", "pos": "verb",
                "example": "Don't forget to save your work.", "pronunciation": "/seɪv/"},
            {"word": "Delete", "meaning": "Xóa", "pos": "verb",
                "example": "Delete unnecessary files.", "pronunciation": "/dɪˈliːt/"},
            {"word": "Copy", "meaning": "Sao chép", "pos": "verb",
                "example": "Copy the text to clipboard.", "pronunciation": "/ˈkɑːpi/"},
            {"word": "Paste", "meaning": "Dán", "pos": "verb",
                "example": "Paste the text here.", "pronunciation": "/peɪst/"},
            {"word": "Search", "meaning": "Tìm kiếm", "pos": "verb",
                "example": "Search for information online.", "pronunciation": "/sɜːrtʃ/"},
            {"word": "Click", "meaning": "Nhấp chuột", "pos": "verb",
                "example": "Click on the icon to open.", "pronunciation": "/klɪk/"},
            {"word": "Type", "meaning": "Gõ phím", "pos": "verb",
                "example": "Type your message here.", "pronunciation": "/taɪp/"},
            {"word": "Connect", "meaning": "Kết nối", "pos": "verb",
                "example": "Connect to the Wi-Fi network.", "pronunciation": "/kəˈnekt/"},
            {"word": "Disconnect", "meaning": "Ngắt kết nối", "pos": "verb",
                "example": "Disconnect from the internet.", "pronunciation": "/ˌdɪskəˈnekt/"},
            {"word": "Install", "meaning": "Cài đặt", "pos": "verb",
                "example": "Install the new software.", "pronunciation": "/ɪnˈstɔːl/"},
            {"word": "Update", "meaning": "Cập nhật", "pos": "verb",
                "example": "Update your software regularly.", "pronunciation": "/ʌpˈdeɪt/"},
            {"word": "Backup", "meaning": "Sao lưu", "pos": "noun",
                "example": "Make a backup of important files.", "pronunciation": "/ˈbækʌp/"},
            {"word": "Virus", "meaning": "Virus máy tính", "pos": "noun",
                "example": "Protect your computer from viruses.", "pronunciation": "/ˈvaɪrəs/"},
            {"word": "Network", "meaning": "Mạng", "pos": "noun",
                "example": "Join the wireless network.", "pronunciation": "/ˈnetwɜːrk/"},
            {"word": "Wi-Fi", "meaning": "Wi-Fi", "pos": "noun",
                "example": "The Wi-Fi signal is strong.", "pronunciation": "/ˈwaɪfaɪ/"},
            {"word": "Bluetooth", "meaning": "Bluetooth", "pos": "noun",
                "example": "Connect via Bluetooth.", "pronunciation": "/ˈbluːtuːθ/"},
            {"word": "Battery", "meaning": "Pin", "pos": "noun",
                "example": "The battery needs charging.", "pronunciation": "/ˈbætəri/"}
        ]
    }
}

# Create the files
base_path = r"c:\Users\An\Desktop\project\learn-english\public\topics"

for file_path, data in pre_intermediate_topics.items():
    full_path = os.path.join(base_path, file_path)

    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    # Write the JSON file
    with open(full_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Created: {file_path}")

print("Pre-Intermediate level files created successfully!")
