import json
import os

# Define Elementary level topics data
elementary_topics = {
    "elementary/fruits-vegetables.json": {
        "id": "fruits-vegetables",
        "name": "Rau củ và trái cây",
        "level": "elementary",
        "icon": "🥕",
        "description": "Các loại rau củ quả tươi ngon và bổ dưỡng",
        "words": [
            {"word": "Fruit", "meaning": "Trái cây", "pos": "noun",
                "example": "Eat more fruit for vitamins.", "pronunciation": "/fruːt/"},
            {"word": "Vegetable", "meaning": "Rau củ", "pos": "noun",
                "example": "Vegetables are good for health.", "pronunciation": "/ˈvedʒtəbəl/"},
            {"word": "Apple", "meaning": "Táo", "pos": "noun",
                "example": "An apple a day keeps the doctor away.", "pronunciation": "/ˈæpəl/"},
            {"word": "Banana", "meaning": "Chuối", "pos": "noun",
                "example": "Monkeys love to eat bananas.", "pronunciation": "/bəˈnænə/"},
            {"word": "Orange", "meaning": "Cam", "pos": "noun",
                "example": "Orange juice is rich in vitamin C.", "pronunciation": "/ˈɔːrɪndʒ/"},
            {"word": "Grape", "meaning": "Nho", "pos": "noun",
                "example": "Grapes are used to make wine.", "pronunciation": "/ɡreɪp/"},
            {"word": "Strawberry", "meaning": "Dâu tây", "pos": "noun",
                "example": "Strawberries are red and sweet.", "pronunciation": "/ˈstrɔːberi/"},
            {"word": "Pineapple", "meaning": "Dứa/Khóm", "pos": "noun",
                "example": "Pineapple is a tropical fruit.", "pronunciation": "/ˈpaɪnæpəl/"},
            {"word": "Mango", "meaning": "Xoài", "pos": "noun",
                "example": "Mango is the king of fruits.", "pronunciation": "/ˈmæŋɡoʊ/"},
            {"word": "Watermelon", "meaning": "Dưa hấu", "pos": "noun",
                "example": "Watermelon is perfect for summer.", "pronunciation": "/ˈwɔːtərmelən/"},
            {"word": "Lemon", "meaning": "Chanh", "pos": "noun",
                "example": "Add lemon to your tea.", "pronunciation": "/ˈlemən/"},
            {"word": "Coconut", "meaning": "Dừa", "pos": "noun",
                "example": "Coconut water is very refreshing.", "pronunciation": "/ˈkoʊkənʌt/"},
            {"word": "Peach", "meaning": "Đào", "pos": "noun",
                "example": "Peaches are soft and juicy.", "pronunciation": "/piːtʃ/"},
            {"word": "Cherry", "meaning": "Cherry", "pos": "noun",
                "example": "Cherries are small and red.", "pronunciation": "/ˈtʃeri/"},
            {"word": "Carrot", "meaning": "Cà rốt", "pos": "noun",
                "example": "Carrots are good for your eyes.", "pronunciation": "/ˈkærət/"},
            {"word": "Potato", "meaning": "Khoai tây", "pos": "noun",
                "example": "French fries are made from potatoes.", "pronunciation": "/pəˈteɪtoʊ/"},
            {"word": "Tomato", "meaning": "Cà chua", "pos": "noun",
                "example": "Tomatoes are used in many dishes.", "pronunciation": "/təˈmeɪtoʊ/"},
            {"word": "Onion", "meaning": "Hành tây", "pos": "noun",
                "example": "Cutting onions makes me cry.", "pronunciation": "/ˈʌnjən/"},
            {"word": "Garlic", "meaning": "Tỏi", "pos": "noun",
                "example": "Garlic adds flavor to food.", "pronunciation": "/ˈɡɑːrlɪk/"},
            {"word": "Cabbage", "meaning": "Bắp cải", "pos": "noun",
                "example": "Cabbage is used in salads.", "pronunciation": "/ˈkæbɪdʒ/"},
            {"word": "Lettuce", "meaning": "Rau xà lách", "pos": "noun",
                "example": "Lettuce is crispy and fresh.", "pronunciation": "/ˈletɪs/"},
            {"word": "Cucumber", "meaning": "Dưa leo", "pos": "noun",
                "example": "Cucumber is very refreshing.", "pronunciation": "/ˈkjuːkʌmbər/"},
            {"word": "Pepper", "meaning": "Ớt/Tiêu", "pos": "noun",
                "example": "This pepper is very spicy.", "pronunciation": "/ˈpepər/"},
            {"word": "Corn", "meaning": "Ngô", "pos": "noun",
                "example": "Corn is a popular vegetable.", "pronunciation": "/kɔːrn/"},
            {"word": "Broccoli", "meaning": "Súp lơ xanh", "pos": "noun",
                "example": "Broccoli is very nutritious.", "pronunciation": "/ˈbrɑːkəli/"},
            {"word": "Spinach", "meaning": "Rau bina", "pos": "noun",
                "example": "Popeye eats spinach for strength.", "pronunciation": "/ˈspɪnɪtʃ/"},
            {"word": "Bean", "meaning": "Đậu", "pos": "noun",
                "example": "Beans are rich in protein.", "pronunciation": "/biːn/"},
            {"word": "Pea", "meaning": "Đậu Hà Lan", "pos": "noun",
                "example": "Green peas are small and round.", "pronunciation": "/piː/"},
            {"word": "Mushroom", "meaning": "Nấm", "pos": "noun",
                "example": "This soup has fresh mushrooms.", "pronunciation": "/ˈmʌʃruːm/"},
            {"word": "Sweet potato", "meaning": "Khoai lang", "pos": "noun",
                "example": "Sweet potatoes are orange inside.", "pronunciation": "/swiːt pəˈteɪtoʊ/"},
            {"word": "Pumpkin", "meaning": "Bí ngô", "pos": "noun",
                "example": "Pumpkin pie is popular in autumn.", "pronunciation": "/ˈpʌmpkɪn/"},
            {"word": "Radish", "meaning": "Củ cải", "pos": "noun",
                "example": "Radishes are crispy and peppery.", "pronunciation": "/ˈrædɪʃ/"},
            {"word": "Celery", "meaning": "Cần tây", "pos": "noun",
                "example": "Celery is crunchy and healthy.", "pronunciation": "/ˈseləri/"},
            {"word": "Fresh", "meaning": "Tươi", "pos": "adjective",
                "example": "Buy fresh vegetables from the market.", "pronunciation": "/freʃ/"},
            {"word": "Ripe", "meaning": "Chín", "pos": "adjective",
                "example": "This banana is perfectly ripe.", "pronunciation": "/raɪp/"}
        ]
    },

    "elementary/clothes.json": {
        "id": "clothes",
        "name": "Quần áo",
        "level": "elementary",
        "icon": "👕",
        "description": "Các loại quần áo và phụ kiện thời trang",
        "words": [
            {"word": "Clothes", "meaning": "Quần áo", "pos": "noun",
                "example": "I need new clothes for work.", "pronunciation": "/kloʊðz/"},
            {"word": "Shirt", "meaning": "Áo sơ mi", "pos": "noun",
                "example": "He wears a white shirt to work.", "pronunciation": "/ʃɜːrt/"},
            {"word": "T-shirt", "meaning": "Áo thun", "pos": "noun",
                "example": "I love wearing t-shirts in summer.", "pronunciation": "/ˈtiː ʃɜːrt/"},
            {"word": "Pants", "meaning": "Quần dài", "pos": "noun",
                "example": "These pants are too tight.", "pronunciation": "/pænts/"},
            {"word": "Jeans", "meaning": "Quần jean", "pos": "noun",
                "example": "Blue jeans are very popular.", "pronunciation": "/dʒiːnz/"},
            {"word": "Shorts", "meaning": "Quần ngắn", "pos": "noun",
                "example": "I wear shorts when it's hot.", "pronunciation": "/ʃɔːrts/"},
            {"word": "Skirt", "meaning": "Váy", "pos": "noun",
                "example": "She looks beautiful in that skirt.", "pronunciation": "/skɜːrt/"},
            {"word": "Dress", "meaning": "Váy liền", "pos": "noun",
                "example": "The bride wore a white dress.", "pronunciation": "/dres/"},
            {"word": "Sweater", "meaning": "Áo len", "pos": "noun",
                "example": "This sweater keeps me warm.", "pronunciation": "/ˈswetər/"},
            {"word": "Jacket", "meaning": "Áo khoác", "pos": "noun",
                "example": "Don't forget your jacket.", "pronunciation": "/ˈdʒækɪt/"},
            {"word": "Coat", "meaning": "Áo choàng", "pos": "noun",
                "example": "Winter coats are very thick.", "pronunciation": "/koʊt/"},
            {"word": "Suit", "meaning": "Bộ vest", "pos": "noun",
                "example": "He wears a suit to business meetings.", "pronunciation": "/suːt/"},
            {"word": "Tie", "meaning": "Cà vạt", "pos": "noun",
                "example": "His tie matches his shirt.", "pronunciation": "/taɪ/"},
            {"word": "Underwear", "meaning": "Đồ lót", "pos": "noun",
                "example": "Change your underwear daily.", "pronunciation": "/ˈʌndərwer/"},
            {"word": "Socks", "meaning": "Tất", "pos": "noun",
                "example": "My socks are wet from the rain.", "pronunciation": "/sɑːks/"},
            {"word": "Shoes", "meaning": "Giày", "pos": "noun",
                "example": "These shoes are very comfortable.", "pronunciation": "/ʃuːz/"},
            {"word": "Boots", "meaning": "Ủng", "pos": "noun",
                "example": "Rain boots keep your feet dry.", "pronunciation": "/buːts/"},
            {"word": "Sneakers", "meaning": "Giày thể thao", "pos": "noun",
                "example": "I wear sneakers when I exercise.", "pronunciation": "/ˈsniːkərz/"},
            {"word": "Sandals", "meaning": "Dép", "pos": "noun",
                "example": "Sandals are perfect for the beach.", "pronunciation": "/ˈsændəlz/"},
            {"word": "Hat", "meaning": "Mũ", "pos": "noun",
                "example": "Wear a hat to protect from sun.", "pronunciation": "/hæt/"},
            {"word": "Cap", "meaning": "Mũ lưỡi trai", "pos": "noun",
                "example": "Baseball players wear caps.", "pronunciation": "/kæp/"},
            {"word": "Gloves", "meaning": "Găng tay", "pos": "noun",
                "example": "Gloves keep your hands warm.", "pronunciation": "/ɡlʌvz/"},
            {"word": "Scarf", "meaning": "Khăn quàng", "pos": "noun",
                "example": "This scarf is very soft.", "pronunciation": "/skɑːrf/"},
            {"word": "Belt", "meaning": "Thắt lưng", "pos": "noun",
                "example": "This belt is too big for me.", "pronunciation": "/belt/"},
            {"word": "Watch", "meaning": "Đồng hồ đeo tay", "pos": "noun",
                "example": "My watch stopped working.", "pronunciation": "/wɑːtʃ/"},
            {"word": "Jewelry", "meaning": "Trang sức", "pos": "noun",
                "example": "She loves wearing jewelry.", "pronunciation": "/ˈdʒuːəlri/"},
            {"word": "Ring", "meaning": "Nhẫn", "pos": "noun",
                "example": "The wedding ring is gold.", "pronunciation": "/rɪŋ/"},
            {"word": "Necklace", "meaning": "Dây chuyền", "pos": "noun",
                "example": "This necklace is very expensive.", "pronunciation": "/ˈnekləs/"},
            {"word": "Earrings", "meaning": "Bông tai", "pos": "noun",
                "example": "Her earrings are beautiful.", "pronunciation": "/ˈɪrɪŋz/"},
            {"word": "Uniform", "meaning": "Đồng phục", "pos": "noun",
                "example": "Students must wear school uniforms.", "pronunciation": "/ˈjuːnɪfɔːrm/"}
        ]
    },

    "elementary/jobs.json": {
        "id": "jobs",
        "name": "Nghề nghiệp",
        "level": "elementary",
        "icon": "👷",
        "description": "Các nghề nghiệp và công việc phổ biến",
        "words": [
            {"word": "Job", "meaning": "Công việc", "pos": "noun",
                "example": "I love my job very much.", "pronunciation": "/dʒɑːb/"},
            {"word": "Work", "meaning": "Làm việc", "pos": "verb",
                "example": "I work in an office.", "pronunciation": "/wɜːrk/"},
            {"word": "Teacher", "meaning": "Giáo viên", "pos": "noun",
                "example": "My mother is a teacher.", "pronunciation": "/ˈtiːtʃər/"},
            {"word": "Doctor", "meaning": "Bác sĩ", "pos": "noun",
                "example": "The doctor examined the patient.", "pronunciation": "/ˈdɑːktər/"},
            {"word": "Nurse", "meaning": "Y tá", "pos": "noun",
                "example": "The nurse is very caring.", "pronunciation": "/nɜːrs/"},
            {"word": "Engineer", "meaning": "Kỹ sư", "pos": "noun",
                "example": "He is a software engineer.", "pronunciation": "/ˌendʒɪˈnɪr/"},
            {"word": "Lawyer", "meaning": "Luật sư", "pos": "noun",
                "example": "The lawyer defended his client.", "pronunciation": "/ˈlɔːjər/"},
            {"word": "Police officer", "meaning": "Cảnh sát", "pos": "noun",
                "example": "The police officer helped the child.", "pronunciation": "/pəˈliːs ˈɔːfɪsər/"},
            {"word": "Firefighter", "meaning": "Lính cứu hỏa", "pos": "noun",
                "example": "Firefighters are very brave.", "pronunciation": "/ˈfaɪərfaɪtər/"},
            {"word": "Chef", "meaning": "Đầu bếp", "pos": "noun",
                "example": "The chef makes delicious food.", "pronunciation": "/ʃef/"},
            {"word": "Waiter", "meaning": "Phục vụ (nam)", "pos": "noun",
             "example": "The waiter took our order.", "pronunciation": "/ˈweɪtər/"},
            {"word": "Waitress", "meaning": "Phục vụ (nữ)", "pos": "noun",
             "example": "The waitress is very friendly.", "pronunciation": "/ˈweɪtrəs/"},
            {"word": "Driver", "meaning": "Tài xế", "pos": "noun",
                "example": "The bus driver is careful.", "pronunciation": "/ˈdraɪvər/"},
            {"word": "Pilot", "meaning": "Phi công", "pos": "noun",
                "example": "The pilot flies the airplane.", "pronunciation": "/ˈpaɪlət/"},
            {"word": "Farmer", "meaning": "Nông dân", "pos": "noun",
                "example": "The farmer grows vegetables.", "pronunciation": "/ˈfɑːrmər/"},
            {"word": "Mechanic", "meaning": "Thợ máy", "pos": "noun",
                "example": "The mechanic fixed my car.", "pronunciation": "/məˈkænɪk/"},
            {"word": "Builder", "meaning": "Thợ xây", "pos": "noun",
                "example": "The builder constructed the house.", "pronunciation": "/ˈbɪldər/"},
            {"word": "Electrician", "meaning": "Thợ điện", "pos": "noun",
                "example": "Call an electrician to fix the lights.", "pronunciation": "/ɪˌlekˈtrɪʃən/"},
            {"word": "Plumber", "meaning": "Thợ sửa ống nước", "pos": "noun",
                "example": "The plumber fixed the leak.", "pronunciation": "/ˈplʌmər/"},
            {"word": "Artist", "meaning": "Nghệ sĩ", "pos": "noun",
                "example": "The artist painted a beautiful picture.", "pronunciation": "/ˈɑːrtɪst/"},
            {"word": "Musician", "meaning": "Nhạc sĩ", "pos": "noun",
                "example": "The musician plays guitar.", "pronunciation": "/mjuˈzɪʃən/"},
            {"word": "Singer", "meaning": "Ca sĩ", "pos": "noun",
                "example": "The singer has a beautiful voice.", "pronunciation": "/ˈsɪŋər/"},
            {"word": "Actor", "meaning": "Diễn viên (nam)", "pos": "noun",
             "example": "The actor starred in many movies.", "pronunciation": "/ˈæktər/"},
            {"word": "Actress", "meaning": "Diễn viên (nữ)", "pos": "noun",
             "example": "She is a famous actress.", "pronunciation": "/ˈæktrəs/"},
            {"word": "Journalist", "meaning": "Nhà báo", "pos": "noun",
                "example": "The journalist wrote an article.", "pronunciation": "/ˈdʒɜːrnəlɪst/"},
            {"word": "Photographer", "meaning": "Nhiếp ảnh gia", "pos": "noun",
                "example": "The photographer took great photos.", "pronunciation": "/fəˈtɑːɡrəfər/"},
            {"word": "Accountant", "meaning": "Kế toán", "pos": "noun",
                "example": "The accountant manages the finances.", "pronunciation": "/əˈkaʊntənt/"},
            {"word": "Manager", "meaning": "Quản lý", "pos": "noun",
                "example": "The manager leads the team.", "pronunciation": "/ˈmænɪdʒər/"},
            {"word": "Secretary", "meaning": "Thư ký", "pos": "noun",
                "example": "The secretary scheduled the meeting.", "pronunciation": "/ˈsekrəteri/"},
            {"word": "Dentist", "meaning": "Nha sĩ", "pos": "noun",
                "example": "Visit the dentist twice a year.", "pronunciation": "/ˈdentɪst/"},
            {"word": "Pharmacist", "meaning": "Dược sĩ", "pos": "noun",
                "example": "The pharmacist prepared the medicine.", "pronunciation": "/ˈfɑːrməsɪst/"},
            {"word": "Veterinarian", "meaning": "Bác sĩ thú y", "pos": "noun",
                "example": "The veterinarian treats animals.", "pronunciation": "/ˌvetərɪˈneriən/"},
            {"word": "Barber", "meaning": "Thợ cắt tóc (nam)", "pos": "noun",
             "example": "The barber cut my hair.", "pronunciation": "/ˈbɑːrbər/"},
            {"word": "Hairdresser", "meaning": "Thợ làm tóc", "pos": "noun",
                "example": "The hairdresser styled her hair.", "pronunciation": "/ˈherdresər/"},
            {"word": "Scientist", "meaning": "Nhà khoa học", "pos": "noun",
                "example": "The scientist made a discovery.", "pronunciation": "/ˈsaɪəntɪst/"}
        ]
    }
}

# Create the files
base_path = r"c:\Users\An\Desktop\project\learn-english\public\topics"

for file_path, data in elementary_topics.items():
    full_path = os.path.join(base_path, file_path)

    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    # Write the JSON file
    with open(full_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Created: {file_path}")

print("Elementary level files created successfully!")
