import json
import os

# Define the remaining topics data
topics_data = {
    # Beginner level
    "beginner/clock.json": {
        "id": "clock",
        "name": "Thời gian & Giờ giấc",
        "level": "beginner",
        "icon": "🕐",
        "description": "Từ vựng về giờ giấc và thời gian trong ngày",
        "words": [
            {"word": "Clock", "meaning": "Đồng hồ", "pos": "noun",
                "example": "The clock shows 3 o'clock.", "pronunciation": "/klɑːk/"},
            {"word": "Time", "meaning": "Thời gian", "pos": "noun",
                "example": "What time is it?", "pronunciation": "/taɪm/"},
            {"word": "Hour", "meaning": "Giờ", "pos": "noun",
                "example": "I waited for one hour.", "pronunciation": "/aʊr/"},
            {"word": "Minute", "meaning": "Phút", "pos": "noun",
                "example": "Wait a minute, please.", "pronunciation": "/ˈmɪnɪt/"},
            {"word": "Second", "meaning": "Giây", "pos": "noun",
                "example": "It takes 60 seconds to make a minute.", "pronunciation": "/ˈsekənd/"},
            {"word": "Morning", "meaning": "Buổi sáng", "pos": "noun",
                "example": "I exercise every morning.", "pronunciation": "/ˈmɔːrnɪŋ/"},
            {"word": "Afternoon", "meaning": "Buổi chiều", "pos": "noun",
                "example": "Good afternoon, everyone!", "pronunciation": "/ˌæftərˈnuːn/"},
            {"word": "Evening", "meaning": "Buổi tối", "pos": "noun",
                "example": "We have dinner in the evening.", "pronunciation": "/ˈiːvnɪŋ/"},
            {"word": "Night", "meaning": "Ban đêm", "pos": "noun",
                "example": "Good night, sleep well!", "pronunciation": "/naɪt/"},
            {"word": "Midnight", "meaning": "Nửa đêm", "pos": "noun",
                "example": "The party ends at midnight.", "pronunciation": "/ˈmɪdnaɪt/"},
            {"word": "Noon", "meaning": "Buổi trưa", "pos": "noun",
                "example": "We eat lunch at noon.", "pronunciation": "/nuːn/"},
            {"word": "Early", "meaning": "Sớm", "pos": "adverb",
                "example": "I wake up early every day.", "pronunciation": "/ˈɜːrli/"},
            {"word": "Late", "meaning": "Muộn", "pos": "adverb",
                "example": "Don't be late for school.", "pronunciation": "/leɪt/"},
            {"word": "On time", "meaning": "Đúng giờ", "pos": "phrase",
                "example": "Please arrive on time.", "pronunciation": "/ɑːn taɪm/"},
            {"word": "Schedule", "meaning": "Lịch trình", "pos": "noun",
                "example": "Check your schedule for tomorrow.", "pronunciation": "/ˈskedʒuːl/"},
            {"word": "Alarm", "meaning": "Báo thức", "pos": "noun",
                "example": "Set the alarm for 7 AM.", "pronunciation": "/əˈlɑːrm/"},
            {"word": "Watch", "meaning": "Đồng hồ đeo tay", "pos": "noun",
                "example": "My watch is very accurate.", "pronunciation": "/wɑːtʃ/"},
            {"word": "Now", "meaning": "Bây giờ", "pos": "adverb",
                "example": "Come here now!", "pronunciation": "/naʊ/"},
            {"word": "Then", "meaning": "Khi đó", "pos": "adverb",
                "example": "First study, then play.", "pronunciation": "/ðen/"},
            {"word": "Soon", "meaning": "Sớm", "pos": "adverb",
                "example": "I'll be there soon.", "pronunciation": "/suːn/"},
            {"word": "Before", "meaning": "Trước", "pos": "preposition",
                "example": "Come before 5 PM.", "pronunciation": "/bɪˈfɔːr/"},
            {"word": "After", "meaning": "Sau", "pos": "preposition",
                "example": "After lunch, we'll go out.", "pronunciation": "/ˈæftər/"},
            {"word": "During", "meaning": "Trong lúc", "pos": "preposition",
                "example": "Don't talk during the movie.", "pronunciation": "/ˈdʊrɪŋ/"},
            {"word": "While", "meaning": "Trong khi", "pos": "conjunction",
                "example": "I read while waiting.", "pronunciation": "/waɪl/"},
            {"word": "Always", "meaning": "Luôn luôn", "pos": "adverb",
                "example": "I always brush my teeth.", "pronunciation": "/ˈɔːlweɪz/"}
        ]
    },

    "beginner/classroom.json": {
        "id": "classroom",
        "name": "Đồ vật trong lớp học",
        "level": "beginner",
        "icon": "📚",
        "description": "Các đồ vật và thiết bị thường thấy trong lớp học",
        "words": [
            {"word": "Classroom", "meaning": "Lớp học", "pos": "noun",
                "example": "Our classroom is very clean.", "pronunciation": "/ˈklæsruːm/"},
            {"word": "Teacher", "meaning": "Giáo viên", "pos": "noun",
                "example": "The teacher is very kind.", "pronunciation": "/ˈtiːtʃər/"},
            {"word": "Student", "meaning": "Học sinh", "pos": "noun",
                "example": "I am a good student.", "pronunciation": "/ˈstuːdənt/"},
            {"word": "Desk", "meaning": "Bàn học", "pos": "noun",
                "example": "Put your books on the desk.", "pronunciation": "/desk/"},
            {"word": "Chair", "meaning": "Ghế", "pos": "noun",
                "example": "Sit down on your chair.", "pronunciation": "/tʃer/"},
            {"word": "Book", "meaning": "Sách", "pos": "noun",
                "example": "This book is very interesting.", "pronunciation": "/bʊk/"},
            {"word": "Notebook", "meaning": "Vở", "pos": "noun",
                "example": "Write notes in your notebook.", "pronunciation": "/ˈnoʊtbʊk/"},
            {"word": "Pen", "meaning": "Bút bi", "pos": "noun",
                "example": "I need a pen to write.", "pronunciation": "/pen/"},
            {"word": "Pencil", "meaning": "Bút chì", "pos": "noun",
                "example": "Use a pencil for the math test.", "pronunciation": "/ˈpensəl/"},
            {"word": "Eraser", "meaning": "Cục tẩy", "pos": "noun",
                "example": "Can I borrow your eraser?", "pronunciation": "/ɪˈreɪsər/"},
            {"word": "Ruler", "meaning": "Thước", "pos": "noun",
                "example": "Use a ruler to draw straight lines.", "pronunciation": "/ˈruːlər/"},
            {"word": "Blackboard", "meaning": "Bảng đen", "pos": "noun",
                "example": "The teacher writes on the blackboard.", "pronunciation": "/ˈblækbɔːrd/"},
            {"word": "Whiteboard", "meaning": "Bảng trắng", "pos": "noun",
                "example": "We have a new whiteboard.", "pronunciation": "/ˈwaɪtbɔːrd/"},
            {"word": "Chalk", "meaning": "Phấn", "pos": "noun",
                "example": "The teacher uses white chalk.", "pronunciation": "/tʃɔːk/"},
            {"word": "Marker", "meaning": "Bút lông", "pos": "noun",
                "example": "This marker is running out of ink.", "pronunciation": "/ˈmɑːrkər/"},
            {"word": "Paper", "meaning": "Giấy", "pos": "noun",
                "example": "I need more paper to write.", "pronunciation": "/ˈpeɪpər/"},
            {"word": "Homework", "meaning": "Bài tập về nhà", "pos": "noun",
                "example": "Don't forget to do your homework.", "pronunciation": "/ˈhoʊmwɜːrk/"},
            {"word": "Test", "meaning": "Bài kiểm tra", "pos": "noun",
                "example": "We have a test tomorrow.", "pronunciation": "/test/"},
            {"word": "Lesson", "meaning": "Bài học", "pos": "noun",
                "example": "Today's lesson is about animals.", "pronunciation": "/ˈlesən/"},
            {"word": "Answer", "meaning": "Câu trả lời", "pos": "noun",
                "example": "What's the answer to this question?", "pronunciation": "/ˈænsər/"},
            {"word": "Question", "meaning": "Câu hỏi", "pos": "noun",
                "example": "Ask me any question.", "pronunciation": "/ˈkwestʃən/"},
            {"word": "Backpack", "meaning": "Ba lô", "pos": "noun",
                "example": "My backpack is heavy today.", "pronunciation": "/ˈbækpæk/"},
            {"word": "Calculator", "meaning": "Máy tính", "pos": "noun",
                "example": "Use a calculator for math problems.", "pronunciation": "/ˈkælkjəleɪtər/"},
            {"word": "Dictionary", "meaning": "Từ điển", "pos": "noun",
                "example": "Look up the word in the dictionary.", "pronunciation": "/ˈdɪkʃəneri/"},
            {"word": "Map", "meaning": "Bản đồ", "pos": "noun",
                "example": "Show me Vietnam on the map.", "pronunciation": "/mæp/"},
            {"word": "Globe", "meaning": "Quả địa cầu", "pos": "noun",
                "example": "The globe shows all countries.", "pronunciation": "/ɡloʊb/"},
            {"word": "Computer", "meaning": "Máy tính", "pos": "noun",
                "example": "We learn computer skills.", "pronunciation": "/kəmˈpjuːtər/"},
            {"word": "Projector", "meaning": "Máy chiếu", "pos": "noun",
                "example": "The projector displays the slides.", "pronunciation": "/prəˈdʒektər/"},
            {"word": "Screen", "meaning": "Màn hình", "pos": "noun",
                "example": "Look at the screen, please.", "pronunciation": "/skriːn/"},
            {"word": "Bell", "meaning": "Chuông", "pos": "noun",
                "example": "The school bell rings at 8 AM.", "pronunciation": "/bel/"},
            {"word": "Flag", "meaning": "Cờ", "pos": "noun",
                "example": "The Vietnamese flag is red.", "pronunciation": "/flæɡ/"},
            {"word": "Clock", "meaning": "Đồng hồ", "pos": "noun",
                "example": "The classroom clock is accurate.", "pronunciation": "/klɑːk/"},
            {"word": "Trash can", "meaning": "Thùng rác", "pos": "noun",
                "example": "Throw the paper in the trash can.", "pronunciation": "/træʃ kæn/"},
            {"word": "Locker", "meaning": "Tủ khóa", "pos": "noun",
                "example": "Keep your books in the locker.", "pronunciation": "/ˈlɑːkər/"},
            {"word": "Supplies", "meaning": "Đồ dùng học tập", "pos": "noun",
                "example": "Buy school supplies for the new year.", "pronunciation": "/səˈplaɪz/"}
        ]
    },

    "beginner/body.json": {
        "id": "body",
        "name": "Bộ phận cơ thể",
        "level": "beginner",
        "icon": "👤",
        "description": "Các bộ phận cơ thể người từ đầu đến chân",
        "words": [
            {"word": "Body", "meaning": "Cơ thể", "pos": "noun",
                "example": "Exercise is good for your body.", "pronunciation": "/ˈbɑːdi/"},
            {"word": "Head", "meaning": "Đầu", "pos": "noun",
                "example": "Wear a helmet to protect your head.", "pronunciation": "/hed/"},
            {"word": "Hair", "meaning": "Tóc", "pos": "noun",
                "example": "Her hair is very long.", "pronunciation": "/her/"},
            {"word": "Face", "meaning": "Mặt", "pos": "noun",
                "example": "Wash your face every morning.", "pronunciation": "/feɪs/"},
            {"word": "Eye", "meaning": "Mắt", "pos": "noun",
                "example": "I have brown eyes.", "pronunciation": "/aɪ/"},
            {"word": "Nose", "meaning": "Mũi", "pos": "noun",
                "example": "She has a small nose.", "pronunciation": "/noʊz/"},
            {"word": "Mouth", "meaning": "Miệng", "pos": "noun",
                "example": "Open your mouth and say 'ah'.", "pronunciation": "/maʊθ/"},
            {"word": "Ear", "meaning": "Tai", "pos": "noun",
                "example": "I can't hear with this ear.", "pronunciation": "/ɪr/"},
            {"word": "Tooth", "meaning": "Răng", "pos": "noun",
                "example": "I have a toothache.", "pronunciation": "/tuːθ/"},
            {"word": "Teeth", "meaning": "Những cái răng", "pos": "noun",
                "example": "Brush your teeth twice a day.", "pronunciation": "/tiːθ/"},
            {"word": "Tongue", "meaning": "Lưỡi", "pos": "noun",
                "example": "The tongue helps us taste food.", "pronunciation": "/tʌŋ/"},
            {"word": "Lip", "meaning": "Môi", "pos": "noun",
                "example": "My lips are dry.", "pronunciation": "/lɪp/"},
            {"word": "Neck", "meaning": "Cổ", "pos": "noun",
                "example": "Turn your neck to the left.", "pronunciation": "/nek/"},
            {"word": "Shoulder", "meaning": "Vai", "pos": "noun",
                "example": "Put the bag on your shoulder.", "pronunciation": "/ˈʃoʊldər/"},
            {"word": "Arm", "meaning": "Cánh tay", "pos": "noun",
                "example": "Raise your right arm.", "pronunciation": "/ɑːrm/"},
            {"word": "Hand", "meaning": "Bàn tay", "pos": "noun",
                "example": "Shake hands with your friend.", "pronunciation": "/hænd/"},
            {"word": "Finger", "meaning": "Ngón tay", "pos": "noun",
                "example": "I cut my finger.", "pronunciation": "/ˈfɪŋɡər/"},
            {"word": "Thumb", "meaning": "Ngón cái", "pos": "noun",
                "example": "The thumb is the strongest finger.", "pronunciation": "/θʌm/"},
            {"word": "Chest", "meaning": "Ngực", "pos": "noun",
                "example": "Take a deep breath into your chest.", "pronunciation": "/tʃest/"},
            {"word": "Back", "meaning": "Lưng", "pos": "noun",
                "example": "My back hurts from sitting too long.", "pronunciation": "/bæk/"},
            {"word": "Stomach", "meaning": "Bụng", "pos": "noun",
                "example": "My stomach is empty.", "pronunciation": "/ˈstʌmək/"},
            {"word": "Leg", "meaning": "Chân", "pos": "noun",
                "example": "I broke my leg playing soccer.", "pronunciation": "/leɡ/"},
            {"word": "Knee", "meaning": "Đầu gối", "pos": "noun",
                "example": "Bend your knees when you lift.", "pronunciation": "/niː/"},
            {"word": "Foot", "meaning": "Bàn chân", "pos": "noun",
                "example": "My foot is swollen.", "pronunciation": "/fʊt/"},
            {"word": "Feet", "meaning": "Những bàn chân", "pos": "noun",
                "example": "My feet are tired from walking.", "pronunciation": "/fiːt/"},
            {"word": "Toe", "meaning": "Ngón chân", "pos": "noun",
                "example": "I stubbed my toe on the table.", "pronunciation": "/toʊ/"},
            {"word": "Skin", "meaning": "Da", "pos": "noun",
                "example": "Protect your skin from the sun.", "pronunciation": "/skɪn/"},
            {"word": "Bone", "meaning": "Xương", "pos": "noun",
                "example": "Drink milk for strong bones.", "pronunciation": "/boʊn/"},
            {"word": "Heart", "meaning": "Tim", "pos": "noun",
                "example": "My heart beats fast when I run.", "pronunciation": "/hɑːrt/"},
            {"word": "Brain", "meaning": "Não", "pos": "noun",
                "example": "Use your brain to solve problems.", "pronunciation": "/breɪn/"}
        ]
    },

    "beginner/countries.json": {
        "id": "countries",
        "name": "Quốc gia và quốc tịch",
        "level": "beginner",
        "icon": "🌍",
        "description": "Tên các quốc gia và quốc tịch phổ biến",
        "words": [
            {"word": "Country", "meaning": "Quốc gia", "pos": "noun",
                "example": "Vietnam is a beautiful country.", "pronunciation": "/ˈkʌntri/"},
            {"word": "Nationality", "meaning": "Quốc tịch", "pos": "noun",
                "example": "What's your nationality?", "pronunciation": "/ˌnæʃəˈnæləti/"},
            {"word": "Vietnam", "meaning": "Việt Nam", "pos": "noun",
                "example": "I'm from Vietnam.", "pronunciation": "/ˌviːetˈnɑːm/"},
            {"word": "Vietnamese", "meaning": "Người Việt Nam", "pos": "adjective",
                "example": "I am Vietnamese.", "pronunciation": "/ˌviːetnəˈmiːz/"},
            {"word": "China", "meaning": "Trung Quốc", "pos": "noun",
                "example": "China is a large country.", "pronunciation": "/ˈtʃaɪnə/"},
            {"word": "Chinese", "meaning": "Người Trung Quốc", "pos": "adjective",
                "example": "He is Chinese.", "pronunciation": "/tʃaɪˈniːz/"},
            {"word": "Japan", "meaning": "Nhật Bản", "pos": "noun",
                "example": "Japan is famous for technology.", "pronunciation": "/dʒəˈpæn/"},
            {"word": "Japanese", "meaning": "Người Nhật", "pos": "adjective",
                "example": "She speaks Japanese fluently.", "pronunciation": "/ˌdʒæpəˈniːz/"},
            {"word": "Korea", "meaning": "Hàn Quốc", "pos": "noun",
                "example": "Korea has delicious food.", "pronunciation": "/kəˈriə/"},
            {"word": "Korean", "meaning": "Người Hàn Quốc", "pos": "adjective",
                "example": "Korean culture is very rich.", "pronunciation": "/kəˈriən/"},
            {"word": "Thailand", "meaning": "Thái Lan", "pos": "noun",
                "example": "Thailand is known for its beaches.", "pronunciation": "/ˈtaɪlænd/"},
            {"word": "Thai", "meaning": "Người Thái", "pos": "adjective",
                "example": "Thai food is spicy.", "pronunciation": "/taɪ/"},
            {"word": "America", "meaning": "Mỹ", "pos": "noun",
                "example": "America is also called the USA.", "pronunciation": "/əˈmerɪkə/"},
            {"word": "American", "meaning": "Người Mỹ", "pos": "adjective",
                "example": "American movies are popular.", "pronunciation": "/əˈmerɪkən/"},
            {"word": "England", "meaning": "Anh", "pos": "noun",
                "example": "England is part of the UK.", "pronunciation": "/ˈɪŋɡlənd/"},
            {"word": "English", "meaning": "Người Anh", "pos": "adjective",
                "example": "English is a global language.", "pronunciation": "/ˈɪŋɡlɪʃ/"},
            {"word": "France", "meaning": "Pháp", "pos": "noun",
                "example": "France is famous for wine.", "pronunciation": "/fræns/"},
            {"word": "French", "meaning": "Người Pháp", "pos": "adjective",
                "example": "French cuisine is world-renowned.", "pronunciation": "/frentʃ/"},
            {"word": "Germany", "meaning": "Đức", "pos": "noun",
                "example": "Germany makes good cars.", "pronunciation": "/ˈdʒɜːrməni/"},
            {"word": "German", "meaning": "Người Đức", "pos": "adjective",
                "example": "German engineering is excellent.", "pronunciation": "/ˈdʒɜːrmən/"},
            {"word": "Italy", "meaning": "Ý", "pos": "noun",
                "example": "Italy has beautiful art.", "pronunciation": "/ˈɪtəli/"},
            {"word": "Italian", "meaning": "Người Ý", "pos": "adjective",
                "example": "Italian pasta is delicious.", "pronunciation": "/ɪˈtæljən/"},
            {"word": "Spain", "meaning": "Tây Ban Nha", "pos": "noun",
                "example": "Spain has warm weather.", "pronunciation": "/speɪn/"},
            {"word": "Spanish", "meaning": "Người Tây Ban Nha", "pos": "adjective",
                "example": "Spanish is spoken in many countries.", "pronunciation": "/ˈspænɪʃ/"},
            {"word": "Russia", "meaning": "Nga", "pos": "noun",
                "example": "Russia is the largest country.", "pronunciation": "/ˈrʌʃə/"},
            {"word": "Russian", "meaning": "Người Nga", "pos": "adjective",
                "example": "Russian winters are very cold.", "pronunciation": "/ˈrʌʃən/"},
            {"word": "India", "meaning": "Ấn Độ", "pos": "noun",
                "example": "India has many languages.", "pronunciation": "/ˈɪndiə/"},
            {"word": "Indian", "meaning": "Người Ấn Độ", "pos": "adjective",
                "example": "Indian food is very spicy.", "pronunciation": "/ˈɪndiən/"},
            {"word": "Australia", "meaning": "Úc", "pos": "noun",
                "example": "Australia has unique animals.", "pronunciation": "/ɔːˈstreɪljə/"},
            {"word": "Australian", "meaning": "Người Úc", "pos": "adjective",
                "example": "Australian accents are distinctive.", "pronunciation": "/ɔːˈstreɪljən/"},
            {"word": "Canada", "meaning": "Canada", "pos": "noun",
                "example": "Canada is north of the USA.", "pronunciation": "/ˈkænədə/"},
            {"word": "Canadian", "meaning": "Người Canada", "pos": "adjective",
                "example": "Canadians are very polite.", "pronunciation": "/kəˈneɪdiən/"},
            {"word": "Brazil", "meaning": "Brazil", "pos": "noun",
                "example": "Brazil is famous for soccer.", "pronunciation": "/brəˈzɪl/"},
            {"word": "Brazilian", "meaning": "Người Brazil", "pos": "adjective",
                "example": "Brazilian music is energetic.", "pronunciation": "/brəˈzɪljən/"},
            {"word": "Mexico", "meaning": "Mexico", "pos": "noun",
                "example": "Mexico has ancient pyramids.", "pronunciation": "/ˈmeksɪkoʊ/"},
            {"word": "Mexican", "meaning": "Người Mexico", "pos": "adjective",
                "example": "Mexican food is flavorful.", "pronunciation": "/ˈmeksɪkən/"},
            {"word": "Language", "meaning": "Ngôn ngữ", "pos": "noun",
                "example": "English is an international language.", "pronunciation": "/ˈlæŋɡwɪdʒ/"},
            {"word": "Culture", "meaning": "Văn hóa", "pos": "noun",
                "example": "Every country has its own culture.", "pronunciation": "/ˈkʌltʃər/"},
            {"word": "Capital", "meaning": "Thủ đô", "pos": "noun",
                "example": "Hanoi is the capital of Vietnam.", "pronunciation": "/ˈkæpɪtəl/"},
            {"word": "City", "meaning": "Thành phố", "pos": "noun",
                "example": "Ho Chi Minh City is very busy.", "pronunciation": "/ˈsɪti/"},
            {"word": "Flag", "meaning": "Cờ", "pos": "noun",
                "example": "Every country has its own flag.", "pronunciation": "/flæɡ/"}
        ]
    }
}

# Create the files
base_path = r"c:\Users\An\Desktop\project\learn-english\public\topics"

for file_path, data in topics_data.items():
    full_path = os.path.join(base_path, file_path)

    # Create directory if it doesn't exist
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    # Write the JSON file
    with open(full_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Created: {file_path}")

print("All beginner level files created successfully!")
